# Generated by Django 3.0.5 on 2020-08-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=250)),
                ('question_type', models.CharField(max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('head_comment', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('temp_answer', models.CharField(max_length=200, null=True)),
                ('impulsiveness_total', models.IntegerField(null=True)),
                ('impulsiveness_attentional', models.IntegerField(null=True)),
                ('impulsiveness_non_planning', models.IntegerField(null=True)),
                ('impulsiveness_motor', models.IntegerField(null=True)),
                ('user', models.ManyToManyField(to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=30, null=True)),
                ('value', models.IntegerField()),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question')),
            ],
        ),
    ]
