# Generated by Django 3.0.5 on 2020-08-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='value',
        ),
    ]
